"use client";

import { ArrowUpRight, ExternalLink } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";

type Case = { id:string; tier:"Physics"|"Data integrity"; title:string; science:string; health:string; tone:"watch"|"background"|"issue"; next:string; source:string; url:string; measured:string; evidence:string; history:string[] };
const cases:Case[] = [
  {id:"SSO-XM-2026-001",tier:"Physics",title:"IRAS 18293−0941",science:"Association candidate",health:"Published research · no live feed",tone:"watch",next:"Test gamma-ray attribution against alternative sources.",source:"MeerKAT / EVN / VLA; research paper",url:"https://arxiv.org/abs/2609.00990",measured:"Multiple archival epochs; EVN: 26 May 2024. Publication: 1 September 2026.",evidence:"Published radio morphology supports jet interaction. The UHE causal link remains unresolved; Fermi may be unrelated. No raw telescope data retained by this board.",history:["22 Sep review: opened as a multi-instrument association candidate.","Review correction: jet–cloud interaction is supported, not conclusively established.","Current reviewed decision: retain candidate; no causal promotion."]},
  {id:"SSO-EXO-2026-001",tier:"Physics",title:"β Pictoris b",science:"Confirmation pending",health:"Research report",tone:"watch",next:"Track independent confirmation and alternative origins.",source:"MeerKAT research preprint",url:"https://arxiv.org/abs/2609.16720",measured:"Observation epochs not recorded here. Preprint: 15 September 2026.",evidence:"Reported polarized emission at 0.85–3.5 GHz; inferred field ≥1.25 kG depends on the emission interpretation. This board has not independently reprocessed the measurements.",history:["23 Sep supplied review: auroral-emission candidate identified.","Current reviewed decision: confirmation pending; no SANSA linkage asserted."]},
  {id:"SSO-IONO-2026-001",tier:"Physics",title:"Hermanus ionospheric changes",science:"Background / watch",health:"Source checks required",tone:"background",next:"Compare with local-time and seasonal baselines.",source:"SANSA; supplied monitoring reports",url:"https://spaceweather.sansa.org.za/",measured:"23 September 2026, 09:02 and 11:27 SAST (reported).",evidence:"Reported foF2 7.55 → 8.35 MHz and hmF2 230.154 → 267.667 km. Daytime variability remains plausible. Original payloads are not attached.",history:["23 Sep review: retain ionospheric movement as watch.","Provenance review: the 11:27 sample was temporarily quarantined.","Latest supplied report: sample reproduced; raw-source capture still required here."]},
  {id:"SSO-FORECAST-20260924",tier:"Physics",title:"24 September geomagnetic outlook",science:"Forecast watch",health:"Historical forecast review",tone:"watch",next:"Compare the issued forecast with subsequent measured conditions.",source:"SANSA outlook; NOAA corroboration reported",url:"https://spaceweather.sansa.org.za/",measured:"Target: 24 September 2026. Exact issue timestamp not retained.",evidence:"Supplied reports describe Ap 25 / Active-to-Minor-Storm with CH96 high-speed-stream effects. This is a forecast record; this board does not establish an observed storm.",history:["Supplied sequence: Active / Ap 20 → Active-to-Minor-Storm / Ap 25.","Comparison review reported NOAA corroboration.","Current reviewed decision: forecast watch; outcome not adjudicated."]},
  {id:"SSO-QA-SURFACES",tier:"Data integrity",title:"Conflicting SANSA surfaces",science:"Assessment restricted",health:"Conflicting snapshots reported",tone:"issue",next:"Capture each response and reconcile embedded measurement times.",source:"SANSA public pages; supplied review sequence",url:"https://spaceweather.sansa.org.za/",measured:"Multiple snapshots reported during 22–23 September 2026.",evidence:"Public pages reportedly expose different dates and values. No raw response archive or hash is available in this UI. Page identity alone cannot select a canonical observation.",history:["Monitoring reviews flagged asynchronous page snapshots.","Current reviewed decision: retain provenance issue; require timestamp arbitration."]},
  {id:"SSO-QA-GAPS",tier:"Data integrity",title:"Missing or stale channels",science:"Dependent scoring paused when invalid",health:"Historical gaps · current state below",tone:"issue",next:"Check measurement age and preserve missing values before deriving changes.",source:"SANSA telemetry; supplied monitoring reports",url:"https://spaceweather.sansa.org.za/",measured:"Wind missing at 22 Sep 09:02; recovery reported at 11:28 SAST.",evidence:"Historical missing-channel episode. Repeated HTTP responses do not establish new observations. The telemetry section below reports its own acquisition status.",history:["22 Sep 09:02 report: solar wind unavailable; preserve null.","22 Sep 11:28 report: wind returned at 312.3 km/s.","Current reviewed decision: retain gap history; do not infer current outage from this record."]},
  {id:"SANSA_20260923_1127",tier:"Data integrity",title:"23 September · 11:27 sample",science:"Admission pending source capture",health:"Reproduction reported",tone:"watch",next:"Capture the official response, source URL and payload hash.",source:"Supplied provenance-resolution report; SANSA prediction surface cited",url:"https://spaceweather.sansa.org.za/",measured:"23 September 2026, 11:27 SAST / 09:27 UTC.",evidence:"Reported values: wind 299.4 km/s; Bz +1.8 nT; Dcx +19.5 nT; T-index 31; foF2 8.35 MHz; hmF2 267.667 km. Reproduction is reported, but the exact page URL and raw response are not attached here.",history:["Initial review: sample reported, then could not be reproduced.","Integrity decision: quarantine; preserve the record and exclude from scoring.","Latest supplied report: reproduced on an official SANSA surface.","UI decision: replace unverified label with reproduction reported; admission awaits captured evidence."]},
];

export default function ReviewBoard({lastPoll}:{lastPoll:string|null}) {
  return <section className="review-board" aria-labelledby="board-title">
    <div className="board-heading"><div><p className="eyebrow">Observatory · reviewed case states</p><h2 id="board-title">Two-tier anomaly board</h2><p>Scientific status and data health, reviewed separately.</p></div><span className="board-version">Review record · 23 Sep 2026</span></div>
    <div className="board-summary"><div><strong>{cases.filter(c=>c.science.includes("candidate")||c.science==="Confirmation pending").length}</strong><span>Research candidates</span></div><div><strong>1</strong><span>Forecast watch</span></div><div><strong>2</strong><span>Open provenance reviews</span></div><div><strong className="poll-time">{lastPoll?new Date(lastPoll).toLocaleTimeString("en-GB",{timeZone:"UTC"})+" UTC":"Pending"}</strong><span>Last completed API request · not a new observation</span></div></div>
    <p className="board-context">These are inherited review summaries, not live detections or independently verified findings. Their original evidence is not attached. Newly collected telemetry retains raw payloads separately; reviewer approvals are not implemented.</p>
    <div className="board-columns">{(["Physics","Data integrity"] as const).map(tier=><section key={tier} className="board-tier"><h3>{tier}<span>{cases.filter(c=>c.tier===tier).length} records</span></h3>{cases.filter(c=>c.tier===tier).map(item=><Sheet key={item.id}><article className="board-card"><SheetTrigger className="board-card-trigger"><span>{item.title}</span><ArrowUpRight size={18}/><span className="sr-only">Open evidence and decision history</span></SheetTrigger><div className="board-badges"><span className={`board-badge ${item.tone}`}>Science: {item.science}</span><span className="board-badge health">Data: {item.health}</span></div><p><b>Next action</b>{item.next}</p></article><SheetContent className="board-detail w-[95vw] sm:max-w-xl overflow-y-auto"><SheetHeader><p className="eyebrow">{item.id}</p><SheetTitle>{item.title}</SheetTitle><SheetDescription>{item.science} · {item.health}</SheetDescription></SheetHeader><div className="board-detail-body"><dl><dt>Source</dt><dd>{item.source}</dd><dt>Measurement time</dt><dd>{item.measured}</dd><dt>Source retrieval time</dt><dd>Not retained in the supplied review record.</dd><dt>Evidence and uncertainty</dt><dd>{item.evidence}</dd><dt>Raw payload / hash</dt><dd>Not captured in this board.</dd></dl><h3>Decision history</h3><p className="reviewer-note">Attribution: assistant review summaries in this conversation. No human board approval is recorded.</p><ol>{item.history.map((event,i)=><li key={i}>{event}</li>)}</ol><div className="board-next"><h3>Next action</h3><p>{item.next}</p></div><a href={item.url} target="_blank" rel="noreferrer">Open reference source <ExternalLink size={16}/></a></div></SheetContent></Sheet>)}</section>)}</div>
  </section>;
}
